Expose orbit minimum sum threshold detection bit via wishbone
lnls-dig/bpm-gw pull request #109
Opened 2024-09-24 18:27 UTC by augustofg

Fixes #98

2024-09-26 12:38 UTC, augustofg commented
@ericonr any comments on the ABI?

2024-09-26 14:23 UTC, ericonr approved these changes

2024-09-26 19:47 UTC, guilhermerc requested changes

2024-09-26 19:47 UTC, guilhermerc commented on hdl/modules/wb_orbit_intlk/wb_orbit_intlk.vhd
> +    intlk_sum_bigger_any_o                     => regs_in.sts_min_sum_bigger_i,
I know you rather not having any layer of indirection, but I'd prefer to keep things consistent. Do you mind using an intermediate signal `sts_min_sum_bigger_i` for connecting `intlk_sum_bigger_any_o` to `regs_in.sts_min_sum_bigger_i` (as done for all the other signals)?

2024-09-26 19:51 UTC, guilhermerc commented on hdl/sim/regs/wb_orbit_intlk_regs_const_pkg.vhd
> +  constant ADDR_ORBIT_INTLK_CTRL:                      std_logic_vector(31 downto 0) := x"00000000";
nit: keep previous indentation maybe?

2024-09-27 11:31 UTC, augustofg commented on hdl/modules/wb_orbit_intlk/wb_orbit_intlk.vhd
> +    intlk_sum_bigger_any_o                     => regs_in.sts_min_sum_bigger_i,
I've added a new commit that removes all unnecessary duplicated signals.

2024-09-27 11:48 UTC, augustofg commented on hdl/sim/regs/wb_orbit_intlk_regs_const_pkg.vhd
> +  constant ADDR_ORBIT_INTLK_CTRL:                      std_logic_vector(31 downto 0) := x"00000000";
This should have been amended to e3eb32171e2f054000245259ac1e2e2f83828147, I didn't noticed it wasn't. The previous VHDL pkg file was converted from Verilog using a famous LLM service, but it lacked half of the constants for the status register. I decided to convert it again using emacs macros to get a reliable result.

2024-09-27 11:53 UTC, guilhermerc approved these changes

2024-09-27 18:10 UTC, merged